# -*- coding: utf-8 -*-
"""slopecsvD.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a8qU1S3NT4QtLW59roJogmu_rWaxAyUB
"""



path = 'grating_sim'
import numpy as np
def Blazedcsv(res,theta,depthF, material, gType, er): #depth is fraction of wavelength
  nm= 10**(-9)
  um=10**(-6)
  duty=0.5
 

  arr=np.ones([res,res])
  arr=(1+0j)*arr
  i,j=0,0
  count=0
  while count < res:
    while i < res:
        while j < count:
            arr[i,j]=er
            j=j+1
        i=i+1
        
    np.savetxt(f'{path}/csvs/{gType}_{material}_slope{theta}_{depthF}_layer{count}_{res}.csv', arr, delimiter=',')
    count=count+1
 
  arrU=np.ones([res,res])
  np.savetxt(f'{path}/csvs/U{res}.csv', arrU, delimiter=',')

  return res



